apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: prakashvelu123/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: EUREKA_SERVER_URL