apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: prakashvelu123/discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: SERVER_PORT
              value: "8761"