apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: prakashvelu123/product-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: EUREKA_SERVER_URL

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: PRODUCT_DB_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: POSTGRES_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: POSTGRES_PASSWORD

            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: REDIS_HOST

            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: REDIS_PORT